#!/bin/sh

cd /var/lib/snapd/snaps/ || exit 1

ls *.snap | cut -d'.' -f1 | sed 's/_/ /' | \
while read app revision; do
    if [ ! -e /etc/systemd/system/snap-$app-$revision.mount ]; then
        cat >/etc/systemd/system/snap-$app-$revision.mount <<EOF
[Unit]
Description=Mount unit for ${app}, revision ${revision}
Before=snapd.service

[Mount]
What=/var/lib/snapd/snaps/${app}_${revision}.snap
Where=/snap/${app}/${revision}
Type=squashfs
Options=nodev,ro,x-gdu.hide

[Install]
WantedBy=multi-user.target
EOF
        systemctl -q enable snap-$app-$revision.mount
        systemctl -q start snap-$app-$revision.mount
    fi
done
